all:
	javac -d classes/ -cp classes/ IllegalNumberException.java
	javac -d classes/ -cp classes/ MMBurgersInterface.java
	javac -d classes/ -cp classes/ MMBurgers.java
	# javac -d classes/ -cp classes/ TestCase1.java
	# java -cp classes/ TestCase1 > output_Rachit_TestCase1.txt
	javac -d classes/ -cp classes/ Tester_temp.java
	java -cp classes/ Tester_temp > output_Rachit_randomTestCase.txt

clean:
	# rm classes/IllegalNumberException.class classes/MMBurgersInterface.class classes/MMBurgers.class classes/TestCase1.class
	rm classes/IllegalNumberException.class classes/MMBurgersInterface.class classes/MMBurgers.class classes/Tester_temp.class