all:
	javac -d classes/ -cp classes/ EmptyTreeException.java
	javac -d classes/ -cp classes/ IllegalIDException.java
	javac -d classes/ -cp classes/ NotEmptyException.java
	javac -d classes/ -cp classes/ OrgHierarchyInterface.java
	javac -d classes/ -cp classes/ OrgHierarchy.java
	javac -d classes/ -cp classes/ TesterBasic.java
	javac -d classes/ -cp classes/ TesterAdv.java
	# javac -d classes/ -cp classes/ Tester3_1.java
	# javac -d classes/ -cp classes/ Tester3_2.java
	# javac -d classes/ -cp classes/ Tester3_3.java
	# javac -d classes/ -cp classes/ Tester3_4.java
	# javac -d classes/ -cp classes/ Tester3_5.java
	# javac -d classes/ -cp classes/ Tester3_6.java
	# javac -d classes/ -cp classes/ Tester3_7.java
	# javac -d classes/ -cp classes/ Tester3_8.java
	# javac -d classes/ -cp classes/ Tester3_9.java
	# javac -d classes/ -cp classes/ Tester3_10.java
	# java -cp classes/ Tester3_1
	# java -cp classes/ Tester3_2
	# java -cp classes/ Tester3_3
	# java -cp classes/ Tester3_4
	# java -cp classes/ Tester3_5
	# java -cp classes/ Tester3_6
	# java -cp classes/ Tester3_7
	# java -cp classes/ Tester3_8
	# java -cp classes/ Tester3_9
	# java -cp classes/ Tester3_10
	java -cp classes/ TesterBasic
	java -cp classes/ TesterAdv


clean:
	rm classes/EmptyTreeException.class classes/IllegalIDException.class ../classes/NotEmptyException.class classes/OrgHierarchyInterface.class classes/OrgHierarchy.class classes/Tester1_1.class

