all:
	javac -d ../classes/ -cp ../classes/ EmptyDequeException.java
	javac -d ../classes/ -cp ../classes/ DequeInterface.java
	javac -d ../classes/ -cp ../classes/ ArrayDeque.java
	javac -d ../classes/ -cp ../classes/ DequeChecker.java
	java -cp ../classes/ DequeChecker

clean:
	rm ../classes/EmptyDequeException.class ../classes/DequeInterface.class ../classes/ArrayDeque.class ../classes/DequeChecker.class
